server:
  port: ${GP2GP_SERVER_PORT:8080}

logging:
  level:
    com.nhs.adaptors.gp2gp: DEBUG

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics

gp2gp:
  storage:
    type: ${GP2GP_STORAGE_TYPE:LocalMock}
    containerName: ${GP2GP_STORAGE_CONTAINER_NAME:}
    azureConnectionString: ${GP2GP_AZURE_STORAGE_CONNECTION_STRING:}
  amqp:
    inboundQueueName: "inbound"
    taskQueueName: "taskQueue"
    brokers: ${GP2GP_AMQP_BROKERS:amqp://localhost:5672}
    exchange: amq.direct
    username: ${GP2GP_AMQP_USERNAME:}
    password: ${GP2GP_AMQP_PASSWORD:}
    maxRedeliveries: ${GP2GP_AMQP_MAX_REDELIVERIES:3}
  mongodb:
    uri: ${GP2GP_MONGO_URI:mongodb://localhost:27017}
    database: ${GP2GP_MONGO_DATABASE_NAME:gp2gp}
    host: ${GP2GP_MONGO_HOST:}
    port: ${GP2GP_MONGO_PORT:}
    username: ${GP2GP_MONGO_USERNAME:}
    password: ${GP2GP_MONGO_PASSWORD:}
    options: ${GP2GP_MONGO_OPTIONS:}
    autoIndexCreation: ${GP2GP_MONGO_AUTO_INDEX_CREATION:true}
    ttl: ${GP2GP_MONGO_TTL:P7D}
    cosmosDbEnabled: ${GP2GP_COSMOS_DB_ENABLED:false}
  gpc:
    url: ${GP2GP_GPC_GET_URL:https://orange.testlab.nhs.uk/B82617/STU3/1/gpconnect/fhir}
    structuredEndpoint: ${GP2GP_GPC_GET_STRUCTURED_ENDPOINT:/Patient/$gpc.getstructuredrecord}
    documentEndpoint: ${GP2GP_GPC_GET_DOCUMENT_ENDPOINT:/Binary/}
    host: ${GP2GP_GPC_HOST:orange.testlab.nhs.uk}
  mhs:
    url: ${GP2GP_MHS_OUTBOUND_URL:http://localhost:8081/mock-mhs-endpoint}
