management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
gp2gp:
  storage:
    type: ${GP2GP_STORAGE_TYPE:LocalMock}
    containerName: ${GP2GP_STORAGE_CONTAINER_NAME:for-nia-testing}
    azureConnectionString: ${GP2GP_AZURE_STORAGE_CONNECTION_STRING:for-nia-testing}