management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics
storage:
  type: ${GP2GP_STORAGE_TYPE:S3}
  containerName: ${GP2GP_STORAGE_CONTAINER_NAME:for-nia-testing}
  azureConnectionString: ${AZURE_STORAGE_CONNECTION_STRING:for-nia-testing}