server:
  port: ${GP2GP_SERVER_PORT:8080}

logging:
  level:
    com.nhs.adaptors.gp2gp: DEBUG

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics

gp2gp:
  largeAttachmentThreshold: ${GP2GP_LARGE_ATTACHMENT_THRESHOLD:4500000} # value in bytes. Default value for Spine is ~4.5MB
  largeEhrExtractThreshold: ${GP2GP_LARGE_ATTACHMENT_THRESHOLD:4500000}
  storage:
    type: ${GP2GP_STORAGE_TYPE:LocalMock}
    containerName: ${GP2GP_STORAGE_CONTAINER_NAME:}
    azureConnectionString: ${GP2GP_AZURE_STORAGE_CONNECTION_STRING:}
    trustStoreUrl: ${GP2GP_SSL_TRUST_STORE_URL:}
    trustStorePassword: ${GP2GP_SSL_TRUST_STORE_PASSWORD:}
  amqp:
    inboundQueueName: "gp2gpInboundQueue"
    inboundQueueConsumerConcurrency: ${GP2GP_MHS_INBOUND_QUEUE_CONSUMER_CONCURRENCY:1}
    taskQueueName: "gp2gpTaskQueue"
    taskQueueConsumerConcurrency: ${GP2GP_TASK_QUEUE_CONSUMER_CONCURRENCY:1}
    brokers: ${GP2GP_AMQP_BROKERS:amqp://localhost:5672}
    exchange: amq.direct
    username: ${GP2GP_AMQP_USERNAME:}
    password: ${GP2GP_AMQP_PASSWORD:}
    maxRedeliveries: ${GP2GP_AMQP_MAX_REDELIVERIES:3}
  mongodb:
    uri: ${GP2GP_MONGO_URI:mongodb://localhost:27017}
    database: ${GP2GP_MONGO_DATABASE_NAME:gp2gp}
    host: ${GP2GP_MONGO_HOST:}
    port: ${GP2GP_MONGO_PORT:}
    username: ${GP2GP_MONGO_USERNAME:}
    password: ${GP2GP_MONGO_PASSWORD:}
    options: ${GP2GP_MONGO_OPTIONS:}
    autoIndexCreation: ${GP2GP_MONGO_AUTO_INDEX_CREATION:true}
    ttl: ${GP2GP_MONGO_TTL:P7D}
    cosmosDbEnabled: ${GP2GP_COSMOS_DB_ENABLED:false}
  gpc:
    url: ${GP2GP_GPC_GET_URL:http://localhost:8090/@ODS_CODE@/STU3/1/gpconnect}
    migrateStructuredEndpoint: ${GP2GP_GPC_STRUCTURED_FHIR_BASE:/fhir}/Patient/$gpc.migratestructuredrecord
    documentEndpoint: ${GP2GP_GPC_DOCUMENTS_FHIR_BASE:/documents/fhir}/Binary/
    patientEndpoint: ${GP2GP_GPC_DOCUMENTS_FHIR_BASE:/documents/fhir}/Patient
    patientDocumentReferenceEndpoint: ${GP2GP_GPC_DOCUMENTS_FHIR_BASE:/documents/fhir}/Patient
    overrideNhsNumber: ${GP2GP_GPC_OVERRIDE_NHS_NUMBER:}
    overrideFromAsid: ${GP2GP_GPC_OVERRIDE_FROM_ASID:}
    overrideToAsid: ${GP2GP_GPC_OVERRIDE_TO_ASID:}
    maxRequestSize: ${GP2GP_GPC_MAX_REQUEST_SIZE:150000000} # default 150MB
    requestingPractitionerSDSUserId: ${GP2GP_REQUESTING_PRACTITIONER_SDS_USER_ID:UNK}
    requestingPractitionerSDSRoleProfileId: ${GP2GP_REQUESTING_PRACTITIONER_SDS_ROLE_PROFILE_ID:UNK}
    requestingPractitionerFamilyName: ${GP2GP_REQUESTING_PRACTITIONER_FAMILY_NAME:ADAPTOR}
    requestingPractitionerGivenName: ${GP2GP_REQUESTING_PRACTITIONER_GIVEN_NAME:GP2GP}
  mhs:
    url: ${GP2GP_MHS_OUTBOUND_URL:http://localhost:8081/mock-mhs-endpoint/accept-only}