server:
  port: ${GP2GP_SERVER_PORT:8080}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics

gp2gp:
  amqp:
    inboundQueueName: "inbound"
    taskQueueName: "taskQueue"
    brokers: ${GP2GP_AMQP_BROKERS:amqp://localhost:5672}
    exchange: amq.direct
    username: ${GP2GP_AMQP_USERNAME:}
    password: ${GP2GP_AMQP_PASSWORD:}
    maxRedeliveries: ${GP2GP_AMQP_MAX_REDELIVERIES:3}
  outbound:
    mhsEndPoint: ${MHS_ENDPOINT:/mock-mhs-endpoint}
    mhsPort: ${MHS_PORT:8081}
