@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title GP2GP System Context Diagram

System(requestor, "Foundation System")
System(spine, "NHS Systems", "SDS, PDS, NHAIS")
System(mhsSystem, "MHS Adaptor System")
System(gp2gpSystem, "GP2GP Adaptor System")
System(sendersSystem, "NME Foundation System")

Rel(requestor, spine, "Uses")
Rel(requestor, mhsSystem, "Sends EHR Requests to")
Rel(mhsSystem, requestor, "Dequeues EHR Responses")
Rel(mhsSystem, gp2gpSystem, "Dequeues EHR Request Messages")
Rel(gp2gpSystem, mhsSystem, "Post EHR Response Messages")
Rel(gp2gpSystem, spine, "Uses")
Rel(mhsSystem, spine, "Uses")
Rel(gp2gpSystem, sendersSystem, "GPConnect requests")
Rel(sendersSystem, gp2gpSystem, "Turn GP2GP On/Off, View GP2GP Message")

@enduml

@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title GP2GP Adaptor Emerging Architecture

Person(requestorGp, "GP/GP Admin", "")
Person(senderGp, "GP/GP Admin", "")

System_Boundary(incumbent, "Incumbent") {
    System(requestor, "Foundation System", "Incumbent supporting GP2GP 2.2b")
    System(requestorDocs, "Document Store", "")
}

System_Boundary(spine, "NHS Systems") {
    System(sds, "SDS", "Spine Directory Service")
    System(pds, "PDS", "Personal Demographics Service")
    ContainerDb(audit, "Audit Store", "")
    ContainerDb(mi, "Management Information Store", "")
}

Enterprise_Boundary(ent, "New Market Entrant") {

    System(mhs, "MHS Adaptor", "Pre-assured MHS adaptor")

    System_Boundary(gp2gpSystem, "GP2GP Adaptor System") {
        Container(gp2gp, "GP2GP API", "Docker image", "\n*FHIR --> HL7 v3\n*Switches On/Off\n*Re-send duplicate EHR Extract\n*EHR Messages for viewing")
        ContainerDb(gp2gpStore, "GP2GP Store", "Database", "")
        Container(logAnalyser, "MI/Audit Log Scraper", "Extracts MI/Audit and forwards to NHS")
        note right of gp2gp
            GP2GP functionality can be turned on/off. Expose an endpoint to action this.
            When off EHR Request nessages will not be processed. Should they be dropped?
        end note
        note right of gp2gpStore
            Stores
            * EHR Extracts
            * EHR State
        end note
        note bottom of logAnalyser
            Requirement to report pending EHR Extracts pending for 24 hours. Can this be done by logs?
        end note
    }

    System(sender, "Foundation System", "NME system")
    System(senderDocs, "Document Store", "")
}

Rel(requestorGp, requestor, "Uses", "HTTPS")
Rel_L(requestor, requestorDocs, "Updates")
Rel(requestor, sds, "Looks up", "Endpoint details")
Rel(requestor, pds, "PDS Advanced Trace/Update Healthcare Provider", "HTTPS")
Rel(requestor, mhs, "Posts", "EHR Request")
Rel(requestor, audit, "Forwards", "messages")
Rel(requestor, mi, "Forwards", "messages")

Rel_D(sender, senderGp, "Uses", "HTTPS")
Rel_Down(mhs, gp2gp, "Dequeues", "EHR Request Message")
Rel_Up(gp2gp, pds, "Checks that", "Patient still registered")
Rel_Up(mhs, sds, "Looks up", "Endpoint details")
Rel_Up(mhs, requestor, "Posts", "EHR Extract")
Rel_Up(logAnalyser, audit, "Forwards", "Audit messages")
Rel_Up(logAnalyser, mi, "Forwards", "MI messages")
Rel_D(gp2gp, sender, "GPConnect", "HTTPS")
Rel_D(gp2gp, gp2gpStore, "GPConnect", "HTTPS")
Rel_U(sender, gp2gp, "Uses", "HTTPS")
Rel_D(gp2gp, gp2gpStore, "Fetches", "EHR Extract records")
Rel_Up(gp2gp, mhs, "Posts", "Ack/Nack/EHR Extract")
Rel(gp2gp, senderDocs, "Document retrieval")
@enduml