server:
  port: ${GP2GP_SERVER_PORT:8080}

spring:
  resources:
    add-mappings: false

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

gp2gp:
  storage:
    type: ${GP2GP_STORAGE_TYPE:LocalMock}
    containerName: ${GP2GP_STORAGE_CONTAINER_NAME:}
    azureConnectionString: ${GP2GP_AZURE_STORAGE_CONNECTION_STRING:}
  amqp:
    inboundQueueName: ${GP2GP_MHS_INBOUND_QUEUE:inbound}
    taskQueueName: ${GP2GP_TASK_QUEUE:gp2gpTaskQueue}
    brokers: ${GP2GP_AMQP_BROKERS:amqp://localhost:5672}
    exchange: amq.direct
    username: ${GP2GP_AMQP_USERNAME:}
    password: ${GP2GP_AMQP_PASSWORD:}
    maxRedeliveries: ${GP2GP_AMQP_MAX_REDELIVERIES:3}
  mongodb:
    uri: ${GP2GP_MONGO_URI:mongodb://localhost:27017}
    database: ${GP2GP_MONGO_DATABASE_NAME:gp2gp}
    host: ${GP2GP_MONGO_HOST:}
    port: ${GP2GP_MONGO_PORT:}
    username: ${GP2GP_MONGO_USERNAME:}
    password: ${GP2GP_MONGO_PASSWORD:}
    options: ${GP2GP_MONGO_OPTIONS:}
    autoIndexCreation: ${GP2GP_MONGO_AUTO_INDEX_CREATION:true}
    ttl: ${GP2GP_MONGO_TTL:P7D}
    cosmosDbEnabled: ${GP2GP_COSMOS_DB_ENABLED:false}
  gpc:
    url: ${GP2GP_GPC_GET_URL:https://192.168.128.16:19192/B82617/STU3/1/gpconnect/structured}
    structuredEndpoint: ${GP2GP_GPC_GET_STRUCTURED_ENDPOINT:/fhir/Patient/$gpc.getstructuredrecord}
    host: ${GP2GP_GPC_HOST:messagingportal.opentest.hscic.gov.uk}
    enableTLS: ${GP2GP_ENABLE_TLS:true}
    enableProxy: ${GP2GP_ENABLE_PROXY:true}
    proxy: ${GP2GP_GPC_HTTP_PROXY:10.1.0.251}
    proxyPort: ${GP2GP_GPC_HTTP_PROXY_PORT:3128}
    clientCert: ${GP2GP_SPINE_CLIENT_CERT:-----BEGIN CERTIFICATE-----
      MIIEMDCCAxigAwIBAgIJAMEDR0Dg/TcyMA0GCSqGSIb3DQEBCwUAMFcxFDASBgNV
      BAoTC05IUyBEaWdpdGFsMREwDwYDVQQLEwhPcGVudGVzdDEsMCoGA1UEAxMjT3Bl
      bnRlc3QgRW5kcG9pbnQgSXNzdWluZyBBdXRob3JpdHkwHhcNMTkxMDE4MTQxOTIw
      WhcNMjkxMDAzMTQxOTIwWjBZMRQwEgYDVQQKDAtOSFMgRGlnaXRhbDERMA8GA1UE
      CwwIb3BlbnRlc3QxLjAsBgNVBAMMJXZwbi1jbGllbnQtMTUyNi5vcGVudGVzdC5o
      c2NpYy5nb3YudWswggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDC+Un1
      Epb9s3XpaGtkmA4h1YigZ9r0z+tutY4BXWEa4gnKq/GeCInLjkV7uAVi0l4SQU5N
      AnQHQ8nHVWAQyF1fw+cu+LhiobeE3mZ3f0cp8UFiz+opH2tX3cnRZmry2KvJF8yr
      GDN2/W7fqyzJT4qZ7pbyWDUnSUzYaH3/GwJfj4EqNeH21GVyGwF0oVace07jIHtR
      8J/6Ar1wHN9NzFD5PoGTi68TNXdAhc5qZiN+p3UMwLuXNVLYy9ftjeez3A0pMim/
      hbFC+ii0apizngR+tyjHxw7uHqXjXWIJvONALC9PqeUJbXZAApvfavJnfX9UfiW5
      wEwwzJNPWP3Lgk+bAgMBAAGjgfwwgfkwCQYDVR0TBAIwADAOBgNVHQ8BAf8EBAMC
      BaAwIAYDVR0lAQH/BBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMB0GA1UdDgQWBBT8
      YitDGwOa0mddxN+Lo4Huuk9EQTAeBglghkgBhvhCAQ0EERYPeGNhIGNlcnRpZmlj
      YXRlMHsGA1UdIwR0MHKAFCDaEuVM9WXP/3P79xE0fUxkvBrHoU+kTTBLMRQwEgYD
      VQQKEwtOSFMgRGlnaXRhbDERMA8GA1UECxMIT3BlbnRlc3QxIDAeBgNVBAMTF09w
      ZW50ZXN0IFJvb3QgQXV0aG9yaXR5ggkA6u0cXbLqKoMwDQYJKoZIhvcNAQELBQAD
      ggEBADL8eJiPue9JIRL5EwRJt9J+KLK7YWkxuMcByRq+O4EQwOq61gyjWOHjjxmG
      haW6uAB559vkpe/QtZc76wtqaqnGGaavWqwXNgn30ekmYmREUZUX3W7vUKM4TuG6
      VuE0rIUfu0NelONff52HzQuv+un58IAs2XFiWU3vvnyGAuiumlyTmmZR0gPilXik
      XF4HBn5Kib4mlBdZWys8iMvbbHygekeO++TFvXWhyLHqQ0BtYoD2boBXfAbQBG37
      MQO1KIM9qMQpdJhUuBCxJ+Luo98CwNgdKqS9uok/0PLdQSswRbe1at3TVXKU7Qx6
      BQ4WsA4Xa4O6X+XpmioikLChFyQ=
      -----END CERTIFICATE-----}
    clientKey: ${GP2GP_SPINE_CLIENT_KEY:-----BEGIN RSA PRIVATE KEY-----
      MIIEpQIBAAKCAQEAwvlJ9RKW/bN16WhrZJgOIdWIoGfa9M/rbrWOAV1hGuIJyqvx
      ngiJy45Fe7gFYtJeEkFOTQJ0B0PJx1VgEMhdX8PnLvi4YqG3hN5md39HKfFBYs/q
      KR9rV93J0WZq8tiryRfMqxgzdv1u36ssyU+Kme6W8lg1J0lM2Gh9/xsCX4+BKjXh
      9tRlchsBdKFWnHtO4yB7UfCf+gK9cBzfTcxQ+T6Bk4uvEzV3QIXOamYjfqd1DMC7
      lzVS2MvX7Y3ns9wNKTIpv4WxQvootGqYs54Efrcox8cO7h6l411iCbzjQCwvT6nl
      CW12QAKb32ryZ31/VH4lucBMMMyTT1j9y4JPmwIDAQABAoIBAQDCwbEWlJMuqOzH
      Uf60ZQ74zQvE7vjQQkCyPbiztEsjR1bwlACuE2lRY7QUeSUoKWq+YW2Njz3HY/dS
      nf1vxjU/S7jKOrg0DcX7ewxvoTu8sbjWs0j7+t6GzoyiFuQN4FD4dkWDQpFl8pGl
      6p66GDIiwSkWuvWdYKLaKMZy5M/iEv0JP+Omny581XUV6YUigV+RGTy7N1Tbf520
      LvpF57uDFM+92L5yis5ARXyhkzSk/b+27wX8MJLuPBLl4WqfY9Oyh2RdWXVzD3cr
      PhaREmRGjeRgmyAEUMGAChvdutOlsXL5aE7vKiBZZ9r58PPMDDDmOs0wyz/cBaiW
      vmAinUQBAoGBAPyOSQLj1eGJbp7QayWwYv6kfBBVdHCLeDQYF+BACbhKpu01pq21
      y5Uz9DHzK9pk2555QmIa25yxPCgYnE9Da7KzidUumIT6VduKSPltTavA9enfup25
      WF/UT/i3WB6wOHqChZDXnCCWy2ktYCfJvCC18gZ4gr3PVVDnJ/MANRzBAoGBAMWh
      +aXEXZGIfWOBFbS9JJmgzzkyBy5zb3CFPQhbfnQZfVIonYj4RC6nCVE7AYLp2/Zn
      w0/2dX7ZMqSHz5ZfDQNu01HDZYtW22JtZ0kO5839yRYuGKQDn61jUYCRF7WDMwXx
      GylGRgb3jQZzzVuZiDGXdm27t5AKqVPgs/i9O9dbAoGAdiEfaWikG/Aqe8JEu8Y7
      J5xMI1+1LQcvXD6AvHV3lmnklkNoCQxlgw5gBBUXx/kw+HkDYdvqKOqFlsOcKT8B
      2v47VCmNUXW+Pwf5hiFoGRQScigho7CT847dMRqg7wnCARuX2d3fuyaNUk7VEQc9
      JZe08u3fSWT3JPZaK0FHloECgYEAtUayJ6OrM79fS/LuRv8q4COJj+vcfHXzpOEB
      r3XE0pdCxSZuAWG/oI8kU7bs1vjNAwIAO4tUEIsHEbVk6oe69wgjmx7AOIPt7SVu
      lKuwYdjEJq0XevG7+B1ed7AecCasmWmjQUOtHdzZJS75EWkNbHeCcHq7j8rHsCEu
      0xw4FHsCgYEAqKTXhsEWEUOSJHUv/y7Z/Y1aBK06UEz42RyWYf8Jyi3bCWwuClbU
      cKIzSKCjAT38sHNrcFAhK6AivL9GnB9KSBWtN4W6ZsSTS0CrORK0jIyaDB/Rpk03
      VAx0e5aAavWe5gHg9oBB44ij1OJUZQ/8qrIudFNLKxNAKvt6C31fjDw=
      -----END RSA PRIVATE KEY-----}
    rootCA: ${GP2GP_SPINE_ROOT_CA_CERT:-----BEGIN CERTIFICATE-----
      MIIDxzCCAq+gAwIBAgIJAL42cEBDgYf+MA0GCSqGSIb3DQEBCwUAMEsxFDASBgNV
      BAoTC05IUyBEaWdpdGFsMREwDwYDVQQLEwhPcGVudGVzdDEgMB4GA1UEAxMXT3Bl
      bnRlc3QgUm9vdCBBdXRob3JpdHkwHhcNMTkxMDE4MTMwMjEwWhcNMjkxMDE1MTMw
      MjEwWjBLMRQwEgYDVQQKEwtOSFMgRGlnaXRhbDERMA8GA1UECxMIT3BlbnRlc3Qx
      IDAeBgNVBAMTF09wZW50ZXN0IFJvb3QgQXV0aG9yaXR5MIIBIjANBgkqhkiG9w0B
      AQEFAAOCAQ8AMIIBCgKCAQEA0fFUb7YZODwvgStDbB93Ek+CrJx1cMIkI3nNyzxt
      KO9X788EI/+LnCJmbcWHKO1Qzx/r/GkPgLc4jPHjdFSj+x+KFNkX8YuXKDGYdr8K
      06YsVt8D8sbcxjc0R/LMHGvxOLmmXoKWgWbnrVwmTB7bkiie32m+c3929ScipqLN
      Og98OoZFj5Yc5LabN1ynrBWyT58ggSZdteehL3Mg65G16HLn0onaXxzQ8wEZvBOW
      gn3wgzdE6XKsOZBKfnyx+EzDrbF9awqKNfcGzDKN0oWI9vOyJsSU8Gy0p8f8QtaH
      p5OQ7/5OKjMfkcsvmzwqRqcTz0Epr+J57YeBzABtqQ3BYwIDAQABo4GtMIGqMB0G
      A1UdDgQWBBQgT0ZB8NPTyqvJG2dXVOJ6f6W0eDB7BgNVHSMEdDBygBQgT0ZB8NPT
      yqvJG2dXVOJ6f6W0eKFPpE0wSzEUMBIGA1UEChMLTkhTIERpZ2l0YWwxETAPBgNV
      BAsTCE9wZW50ZXN0MSAwHgYDVQQDExdPcGVudGVzdCBSb290IEF1dGhvcml0eYIJ
      AL42cEBDgYf+MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAEHxGXTj
      nb7Y2GEHuUHdhXFPoCYWCPmXiE6IBzBxqv8/nWcvrnhK+6XpV3OHWxKrDORURx8L
      m4+YR0Es7M2EuH3MSJyI44vbenSDTIPRuywhlKz53jTQEeyxlhs4+G9gTgs37FZj
      2JrVOMAnoWO6GnEL0Wdxjkh+092XIno8sd/y8yWCIWToJY1u9ys9q04rxgq7/eRI
      Ml/glTCTJBO2/7KJdrkdEGyOV3zw6PMfHTEYIM7/6IMau/zV02luzQQABQ3AD21K
      rspO6zqeIui+gOC6i5OnX4xaSb6H4/cF193h9z8TyfIz0pkF8sz/AU+fhPV3c31x
      nvAmCpk97rE/uVE=
      -----END CERTIFICATE-----}
    subCA: ${GP2GP_SPINE_SUB_CA_CERT:-----BEGIN CERTIFICATE-----
      MIID0zCCArugAwIBAgIJAOrtHF2y6iqDMA0GCSqGSIb3DQEBCwUAMEsxFDASBgNV
      BAoTC05IUyBEaWdpdGFsMREwDwYDVQQLEwhPcGVudGVzdDEgMB4GA1UEAxMXT3Bl
      bnRlc3QgUm9vdCBBdXRob3JpdHkwHhcNMTkxMDE4MTMyMTM3WhcNMjkxMDE0MTMy
      MTM3WjBXMRQwEgYDVQQKEwtOSFMgRGlnaXRhbDERMA8GA1UECxMIT3BlbnRlc3Qx
      LDAqBgNVBAMTI09wZW50ZXN0IEVuZHBvaW50IElzc3VpbmcgQXV0aG9yaXR5MIIB
      IjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu4pxlFvYpYDkRa0XBwyO2+He
      g9lrtFgxqv/7JTAKn3CIE173rtLOYDr4ugbFSQNsDYJfYPI9E4g3+mFI6FUEE7dL
      zbNtxoJsB0ns7gLWDKP4PPVY5RgIMnp4MT1awSvjDl9L2gorjUO9Kc243BQFHqr8
      PXRnf+9mogulbJSOJ0OwhGdMKeu9BRRsHPfL8ZZzpuT0yfE3KcF/Fq8tyJyK6H1x
      1t4OOPZnWZH6Sf+wdxmhBZ00kSzQ8xLHgcE9CIIjL+BTENm2DkMCcBJibxeNLEqA
      su3ddnVRmEAAF4EiO68F7qt8AsgQO7hZPeIZy7rTUi4QfazgZeI/wgtDVt5lZQID
      AQABo4GtMIGqMB0GA1UdDgQWBBQg2hLlTPVlz/9z+/cRNH1MZLwaxzB7BgNVHSME
      dDBygBQgT0ZB8NPTyqvJG2dXVOJ6f6W0eKFPpE0wSzEUMBIGA1UEChMLTkhTIERp
      Z2l0YWwxETAPBgNVBAsTCE9wZW50ZXN0MSAwHgYDVQQDExdPcGVudGVzdCBSb290
      IEF1dGhvcml0eYIJAL42cEBDgYf+MAwGA1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEL
      BQADggEBAA88rHaN440jETrRngYFfVLf/JgXI6zokvzc5/t9XkVqjG1yy1AFjPoM
      1qa0w6MhOVeqX7jKj7Y2aLBOKIKPduLIsxV43DLmmrgM+xLixxQSWv1503QvGzcF
      R3NfWpigPTaltx1ERqqJbvosqA7SNQsjz3ldI8J7I7VfkUUn0E3L7C2NPouyGh1h
      DWMB1rzU5E/oWSbqSZE3khlc9r497AWGghd6eoYCWFZiiQdcl4kDKGozja37nIUy
      Uqzclg+HrNLhbVuuieINo6t7JCYV048vXjDcl93o7DOsEL0Uk3JWmuv2nclEYL1s
      lD7W2hACBjl2MP8E/iFx10iOQUwdMPE=
      -----END CERTIFICATE-----}