server:
  port: ${GP2GP_SERVER_PORT:8080}

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings
gp2gp:
  storage:
    type: ${GP2GP_STORAGE_TYPE:Azure}
    containerName: ${GP2GP_STORAGE_CONTAINER_NAME:for-nia-testing}
    azureConnectionString: ${GP2GP_AZURE_STORAGE_CONNECTION_STRING:for-nia-testing}