server:
  port: ${GP2GP_SERVER_PORT:8080}

spring:
  resources:
    add-mappings: false

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings

gp2gp:
  storage:
    type: ${GP2GP_STORAGE_TYPE:LocalMock}
    containerName: ${GP2GP_STORAGE_CONTAINER_NAME:}
    azureConnectionString: ${GP2GP_AZURE_STORAGE_CONNECTION_STRING:}
  amqp:
    inboundQueueName: ${GP2GP_MHS_INBOUND_QUEUE:inbound}
    taskQueueName: ${GP2GP_TASK_QUEUE:gp2gpTaskQueue}
    brokers: ${GP2GP_AMQP_BROKERS:amqp://localhost:5672}
    exchange: amq.direct
    username: ${GP2GP_AMQP_USERNAME:}
    password: ${GP2GP_AMQP_PASSWORD:}
    maxRedeliveries: ${GP2GP_AMQP_MAX_REDELIVERIES:3}
  mongodb:
    uri: ${GP2GP_MONGO_URI:mongodb://localhost:27017}
    database: ${GP2GP_MONGO_DATABASE_NAME:gp2gp}
    host: ${GP2GP_MONGO_HOST:}
    port: ${GP2GP_MONGO_PORT:}
    username: ${GP2GP_MONGO_USERNAME:}
    password: ${GP2GP_MONGO_PASSWORD:}
    options: ${GP2GP_MONGO_OPTIONS:}
    autoIndexCreation: ${GP2GP_MONGO_AUTO_INDEX_CREATION:true}
    ttl: ${GP2GP_MONGO_TTL:P7D}
    cosmosDbEnabled: ${GP2GP_COSMOS_DB_ENABLED:false}
  gpc:
    url: ${GP2GP_GPC_GET_URL:https://messagingportal.opentest.hscic.gov.uk:19192/B82617/STU3/1/gpconnect/structured} 192.168.128.16
    structuredEndpoint: ${GP2GP_GPC_GET_STRUCTURED_ENDPOINT:/fhir/Patient/$gpc.getstructuredrecord}
    host: ${GP2GP_GPC_HOST:messagingportal.opentest.hscic.gov.uk}
    enableTLS: ${GP2GP_ENABLE_TLS:true}
    enableProxy: ${GP2GP_ENABLE_PROXY:false}
    proxy: ${GP2GP_GPC_HTTP_PROXY:10.1.0.251}
    proxyPort: ${GP2GP_GPC_HTTP_PROXY_PORT:3128}
    clientCert: ${GP2GP_SPINE_CLIENT_CERT:}
    clientKey: ${GP2GP_SPINE_CLIENT_KEY:}
    rootCA: ${GP2GP_SPINE_ROOT_CA_CERT:}
    subCA: ${GP2GP_SPINE_SUB_CA_CERT:}