server:
  port: ${GP2GP_SERVER_PORT:8080}

gp2gp:
  amqp:
    inboundQueueName: "inbound"
    taskQueueName: "taskQueue"
    brokers: ${GP2GP_AMQP_BROKERS:amqp://localhost:5672}
    exchange: amq.direct
    username: ${GP2GP_AMQP_USERNAME:}
    password: ${GP2GP_AMQP_PASSWORD:}
    maxRedeliveries: ${GP2GP_AMQP_MAX_REDELIVERIES:3}
