# An override for docker-compose.yml to run e2e tests
version: '3.4'

services:
  gpcc-mock:
    container_name: gpcc-mock
    build: ./gpcc-mock
    ports:
      - "8090:8080"
      - "8080"
    command:
      - -global-response-templating
      - --verbose
    networks: 
      - commonforgp2gp

  gpc-api-mock:
    container_name: gpc-api-mock
    build: ./gpc-api-mock
    ports:
      - "8091:8080"
      - "8080"
    command:
      - -global-response-templating
      - --verbose
    networks: 
      - commonforgp2gp

  sds-api-mock:
    container_name: sds-api-mock
    build: ./sds-api-mock
    ports:
      - "8092:8080"
      - "8080"
    environment:
      - GPC_CONSUMER_OVERRIDE_GPC_PROVIDER_URL
    command:
      - -global-response-templating
      - --verbose
      - --permitted-system-keys=GPC_CONSUMER_OVERRIDE_GPC_PROVIDER_URL
    networks: 
      - commonforgp2gp

networks:
  commonforgp2gp:
    external: true