# An override for docker-compose.yml to run all tests
version: '3.4'

services:
  gp2gp:
    container_name: tests
    build:
      target: build
    entrypoint: "gradle check"
    environment:
      - GP2GP_SERVER_PORT=8080
      - GP2GP_MONGO_URI=mongodb://mongodb:27017
      - GP2GP_MONGO_DATABASE_NAME=gp2gp
      - GP2GP_MONGO_TTL=P30D
      - GP2GP_COSMOS_DB_ENABLED=false
      - DISABLE_TEST_CONTAINERS=true
