version: '3'

services:
  gp2gp:
    image: uk.nhs/gp2gp:latest
    ports:
      - "8080:8080"
    environment:
      - GP2GP_SERVER_PORT=8080
      - GP2GP_STORAGE_TYPE
      - GP2GP_STORAGE_CONTAINER_NAME
      - AZURE_STORAGE_CONNECTION_STRING
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
