version: '3.4'

services:
  gp2gp:
    build:
      context: ../
      dockerfile: docker/service/Dockerfile
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    environment:
      - GP2GP_MONGO_URI=mongodb://mongodb:27017
      - GP2GP_MONGO_DATABASE_NAME=gp2gp
      - GP2GP_MONGO_TTL=P30D
      - GP2GP_COSMOS_DB_ENABLED=false
      - GP2GP_SERVER_PORT=8080
      - GP2GP_STORAGE_TYPE
      - GP2GP_STORAGE_CONTAINER_NAME
      - AZURE_STORAGE_CONNECTION_STRING
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
