# An override for docker-compose.yml to run e2e tests
version: '3.4'

services:
  gp2gp-e2e-tests:
    container_name: e2e-tests
    build:
      context: ../
      dockerfile: docker/e2e-tests/Dockerfile
    depends_on:
      - mongodb
      - activemq
      - gp2gp
      - mock-mhs-adaptor
      - wiremock
    environment:
      - GP2GP_AMQP_BROKERS
      - GP2GP_MONGO_URI
      - GP2GP_MONGO_DATABASE_NAME
      - GP2GP_GPC_GET_URL
      - GP2GP_GPC_GET_STRUCTURED_ENDPOINT
      - GP2GP_GPC_GET_DOCUMENT_ENDPOINT
