version: '3.4'

services:
  integration_tests:
    container_name: tests
    build:
      context: ../
      dockerfile: docker/service/Dockerfile
      target: test
    depends_on:
      - mongodb
    entrypoint: "./gradlew check"
    environment:
      - GP2GP_SERVER_PORT=8080
      - GP2GP_MONGO_URI=mongodb://mongodb:27017
      - GP2GP_MONGO_DATABASE_NAME=gp2gp
      - GP2GP_MONGO_TTL=P30D
      - GP2GP_COSMOS_DB_ENABLED=false
      - DISABLE_TEST_CONTAINERS=true

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
