version: '3.4'

services:
  gp2gp:
    image: ${GP2GP_IMAGE:-local/gp2gp:latest}
    networks: 
      - commonforgp2gp
    build:
      context: ../
      dockerfile: docker/service/Dockerfile
    depends_on:
      - mongodb
      - activemq
    ports:
      - "8080:8080"
    environment:
      - GP2GP_SERVER_PORT
      - GP2GP_LOGGING_LEVEL
      - GP2GP_AMQP_BROKERS
      - GP2GP_AMQP_USERNAME
      - GP2GP_AMQP_PASSWORD
      - GP2GP_AMQP_MAX_REDELIVERIES
      - GP2GP_MONGO_URI
      - GP2GP_MONGO_DATABASE_NAME
      - GP2GP_MONGO_TTL
      - GP2GP_COSMOS_DB_ENABLED
      - GP2GP_STORAGE_TYPE
      - GP2GP_STORAGE_CONTAINER_NAME
      - GP2GP_MHS_OUTBOUND_URL
      - AZURE_STORAGE_CONNECTION_STRING
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - GP2GP_GPC_GET_URL
      - GP2GP_GPC_DOCUMENTS_FHIR_BASE
      - GP2GP_GPC_STRUCTURED_FHIR_BASE
      - GP2GP_SSL_TRUST_STORE_URL
      - GP2GP_SSL_TRUST_STORE_PASSWORD
      - GP2GP_GPC_OVERRIDE_NHS_NUMBER
      - GP2GP_GPC_OVERRIDE_FROM_ASID
      - GP2GP_GPC_OVERRIDE_TO_ASID
      - GP2GP_GPC_GET_TEST_URL
      - GP2GP_LARGE_ATTACHMENT_THRESHOLD

  mock-mhs-adaptor:
    networks: 
      - commonforgp2gp
    build:
      context: ../
      dockerfile: docker/mock-mhs-adaptor/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MOCK_MHS_SERVER_PORT=8081
      - MOCK_MHS_LOGGING_LEVEL
      - MHS_MOCK_REQUEST_JOURNAL_ENABLED
      - GP2GP_MHS_INBOUND_QUEUE=inbound
      - GP2GP_AMQP_BROKERS=amqp://activemq:5672
      - GP2GP_AMQP_USERNAME
      - GP2GP_AMQP_PASSWORD
      - GP2GP_AMQP_MAX_REDELIVERIES

  mongodb:
    networks: 
      - commonforgp2gp
    image: bitnami/mongodb
    ports:
      - "27017:27017"

  activemq:
    networks: 
      - commonforgp2gp
    build:
      context: ./activemq
    ports:
      - "8161:8161"
      - "5672:5672"

  wiremock:
    networks: 
      - commonforgp2gp
    build: ./wiremock
    ports:
      - "8110:8080"
    command:
      - -global-response-templating

  integration-wiremock:
    networks:
      - commonforgp2gp
    build: ./integration-wiremock
    ports:
      - "8111:8080"
    command:
      - -global-response-templating

  gpcc:
    image: nhsdev/nia-gpc-consumer-adaptor:0.1.5
    networks: 
      - commonforgp2gp
    ports:
      - "8090:8090"
    environment:
      - GPC_CONSUMER_LOGGING_LEVEL
      - GPC_CONSUMER_SERVER_PORT
      - GPC_CONSUMER_SPINE_CLIENT_CERT
      - GPC_CONSUMER_SPINE_CLIENT_KEY
      - GPC_CONSUMER_SPINE_ROOT_CA_CERT
      - GPC_CONSUMER_SPINE_SUB_CA_CERT
      - GPC_CONSUMER_OVERRIDE_GPC_PROVIDER_URL
      - GPC_CONSUMER_SEARCH_DOCUMENTS_PATH
      - GPC_CONSUMER_GPC_STRUCTURED_PATH
      - GPC_CONSUMER_GPC_GET_PATIENT_PATH
      - GPC_CONSUMER_GPC_GET_DOCUMENT_PATH
      - GPC_CONSUMER_SDS_URL
      - GPC_CONSUMER_SDS_APIKEY
      - GPC_ENABLE_SDS

  gpconnect-db:
    image: mariadb
    networks: 
      - commonforgp2gp
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=gpconnectdbuser
      - MYSQL_PASSWORD=gpc0nn3ct
      - MYSQL_DATABASE=gpconnect1_5
    command: [
        '--wait_timeout=28800',
    ]

  gpconnect-api:
    image: nhsdigitalmait/gpconnect:1.5.1
    restart : always
    ports:
        - 5000:19191
    networks: 
      - commonforgp2gp
    environment:
      - TZ=Europe/London
      - DATABASE_ADDRESS=gpconnect-db
      - DATABASE_USERNAME=gpconnectdbuser
      - DATABASE_PASSWORD=gpc0nn3ct
      - DATABASE_SCHEMA=gpconnect1_5
      - SERVER_BASE_URL=https://data.developer.nhs.uk/B82617/STU3/1/gpconnect/fhir
      - CONTEXT_PATH=/B82617/STU3/1/gpconnect/
    links:
      - gpconnect-db
    depends_on:
      - gpconnect-db

  tkw:
    image: nhsdigitalmait/tkw_gpconnect_simulator:1.5.1
    restart : always
    ports:
        - 4854:4854
    networks: 
      - commonforgp2gp
    environment:
      - TZ=Europe/London
    links:
      - gpconnect-api
    depends_on:
      - gpconnect-api

  ssp-nginx:
    networks:
      - commonforgp2gp
    links:
      - wiremock:wiremock
    depends_on:
      - wiremock
    build:
      context: ./nginx
    ports:
      - "5555:80"

  gpcc-mock:
    networks: 
      - commonforgp2gp
    build: ./gpcc-mock
    ports:
      - "8112:8080"
    command:
      - -global-response-templating

  gpc-api-mock:
    networks: 
      - commonforgp2gp
    build: ./gpc-api-mock
    ports:
      - "8113:8080"
    command:
      - -global-response-templating
networks:
  commonforgp2gp:
    external: true
