# An override for docker-compose.yml to run e2e tests
version: '3.4'

services:
  gp2gp-e2e-tests:
    container_name: e2e-tests
    build:
      context: ../
      dockerfile: docker/e2e-tests/Dockerfile
    depends_on:
      - mongodb
      - activemq
      - gp2gp
      - mock-mhs-adaptor
    environment:
      - GP2GP_AMQP_BROKERS
      - GP2GP_MONGO_URI
      - GP2GP_MONGO_DATABASE_NAME
      - GP2GP_GPC_GET_URL
      - GP2GP_GPC_GET_STRUCTURED_ENDPOINT
      - GP2GP_GPC_GET_DOCUMENT_ENDPOINT

  gpcc:
    image: nhsdev/nia-gpc-consumer-adaptor:0.0.1
    ports:
      - "8090:8080"
    environment:
      - GPC_CONSUMER_SERVER_PORT
      - GPC_CONSUMER_SPINE_CLIENT_CERT
      - GPC_CONSUMER_SPINE_CLIENT_KEY
      - GPC_CONSUMER_SPINE_ROOT_CA_CERT
      - GPC_CONSUMER_SPINE_SUB_CA_CERT
      - GPC_CONSUMER_URL
      - GPC_CONSUMER_GPC_GET_URL
      - GPC_CONSUMER_SEARCH_DOCUMENTS_PATH
      - GPC_CONSUMER_GPC_STRUCTURED_PATH
      - GPC_CONSUMER_GPC_GET_PATIENT_PATH
      - GPC_CONSUMER_GPC_GET_DOCUMENT_PATH
      - GPC_CONSUMER_SDS_URL
      - GPC_CONSUMER_SDS_APIKEY