version: '3'

services:
  gp2gp:
    image: uk.nhs/gp2gp:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - GP2GP_SERVER_PORT=8080
      - GP2GP_STORAGE_TYPE
      - GP2GP_STORAGE_CONTAINER_NAME
      - AZURE_STORAGE_CONNECTION_STRING
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
mongodb:
  uri: ${GP2GP_MONGO_URI:mongodb://localhost:27017}
  database: ${GP2GP_MONGO_DATABASE_NAME:gp2gp}
  host: ${GP2GP_MONGO_HOST:}
  port: ${GP2GP_MONGO_PORT:}
  username: ${GP2GP_MONGO_USERNAME:}
  password: ${GP2GP_MONGO_PASSWORD:}
  options: ${GP2GP_MONGO_OPTIONS:}
  autoIndexCreation: ${GP2GP_MONGO_AUTO_INDEX_CREATION:true}
  ttl: ${GP2GP_MONGO_TTL:P30D}
  cosmosDbEnabled: ${GP2GP_COSMOS_DB_ENABLED:false}
