# An override for docker-compose.yml to run e2e tests
version: '3.4'

services:
  gp2gp-e2e-tests:
    container_name: e2e-tests
    build:
      context: ../
      dockerfile: docker/e2e-tests/Dockerfile
    depends_on:
      - mongodb
      - activemq
      - gp2gp
      - mock-mhs-adaptor
      - gpcc
      - wiremock
    environment:
      - GP2GP_AMQP_BROKERS
      - GP2GP_MONGO_URI
      - GP2GP_MONGO_DATABASE_NAME
      - GP2GP_GPC_GET_URL
      - GP2GP_GPC_STRUCTURED_FHIR_BASE
      - GP2GP_GPC_GET_DOCUMENT_ENDPOINT
      - GPC_CONSUMER_URL
      - GPC_CONSUMER_GPC_GET_URL
      - GPC_CONSUMER_SDS_URL
      - GPC_CONSUMER_SEARCH_DOCUMENTS_PATH
      - GPC_CONSUMER_GPC_STRUCTURED_PATH
      - GPC_CONSUMER_GPC_GET_PATIENT_PATH
      - GPC_CONSUMER_GPC_GET_DOCUMENT_PATH
      - GP2GP_LARGE_ATTACHMENT_THRESHOLD
    networks: 
      - commonforgp2gp
networks:
  commonforgp2gp:
    external: true