# An override for docker-compose.yml to run all tests
version: '3.4'

services:
  gp2gp:
    container_name: tests
    build:
      target: build
    entrypoint: "gradle check"
    environment:
      - DISABLE_TEST_CONTAINERS=true
