version: '3'

services:
  gp2gp:
    image: uk.nhs/gp2gp:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    environment:
      - GP2GP_SERVER_PORT=8080

  activemq:
    build:
      context: ./activemq
    ports:
      - "8161:8161"
      - "5672:5672"