# An override for docker-compose.yml to run e2e tests
version: '3.4'

services:
  gpcc-mock:
    container_name: gpcc-mock
    build: ./gpcc-mock
    ports:
      - "8090:8080"
      - "8080"
    command:
      - -global-response-templating
      - --verbose
    networks: 
      - commonforgp2gp

networks:
  commonforgp2gp:
    external: true