# An override for docker-compose.yml to run all tests
version: '3.4'

services:
  gp2gp:
    container_name: tests
    build:
      target: build
    entrypoint: "gradle check"
    environment:
      - DISABLE_TEST_CONTAINERS=true
      - GP2GP_GPC_GET_URL=http://wiremock:8080/GP0001/STU3/1/gpconnect
