@startuml 
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

title GP2GP Hybrid Adapter - Patient moves from NME to Incumbent

LAYOUT_WITH_LEGEND()

Person(gp, "Incumbent Admin", "GP Admin staff registering a patient")
System_Ext(incumbent, "Incumbent Foundation System", "Makes the initial request for patient data and ingests that data")

System_Ext(spine, "Spine", "Personal Demographics Service\nSpine Directory Service\nTransaction Messaging Service\nNHAIS")

Enterprise_Boundary(ent, "New Market Entrant") {
    System(adaptor, "GP2GP Adaptor", "Gets GPConnect FHIR data and documents, tranforms into HL7 STU3 and sends to incumbent")
    System_Ext(nme, "New Market Entrant Foundation System", "Provides patient data via GPConnect")
}

Rel(gp, incumbent, "Registers patient")
Rel_R(incumbent, spine, "Searches PDS, updates PDS, gets endpoints from SDS, messaging with TMS")
Rel_L(spine, incumbent, "Sends response messages")
Rel_(spine, adaptor, "Forward-reliable messaging, endpoint lookup", "<-->")
Rel_R(adaptor, nme, "Get Structured Record and document requests")
Rel(nme, spine, "Deduction")

@enduml
