server:
  port: ${MOCK_MHS_SERVER_PORT:8081}

logging:
  level:
    uk:
      nhs:
        adaptors:
          mockmhsservice: DEBUG

management:
  endpoints:
    web:
      base-path: /
      path-mapping.health: healthcheck
      exposure:
        include: info, health, metrics, mappings


gp2gp:
  amqp:
    inboundQueueName: ${GP2GP_MHS_INBOUND_QUEUE:inbound}
    brokers: ${GP2GP_AMQP_BROKERS:amqp://localhost:5672}
    exchange: amq.direct
