server:
  port: ${MOCK_MHS_SERVER_PORT:8081}

gp2gp:
  amqp:
    inboundQueueName: ${GP2GP_MHS_INBOUND_QUEUE:inbound}
    brokers: ${GP2GP_AMQP_BROKERS:amqp://localhost:5672}
    exchange: amq.direct
