version: '3.9'

services:
  gpcc-mock:
    networks: 
      - commonforgp2gp
    build: ./gpcc-mock
    ports:
      - "8080:8080"
    command:
      - -global-response-templating

  gpc-api-mock:
    networks: 
      - commonforgp2gp
    build: ./gpc-api-mock
    ports:
      - "8080:8080"
    command:
      - -global-response-templating
networks:
  commonforgp2gp:
    external: true